"""Render paper-safe V9 result macros from frozen scientific decisions."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def build(root: Path) -> Path:
    decisions = {experiment: _decision(root, experiment) for experiment in ("e2c", "e3c", "e4c", "e5c", "e7c")}
    e2c = decisions["e2c"]
    e3c = decisions["e3c"]
    e4c = decisions["e4c"]
    e5c = decisions["e5c"]
    e7c = decisions["e7c"]
    e2m = e2c.get("metrics", {})
    e3m = e3c.get("metrics", {})
    e4m = e4c.get("metrics", {})
    e5m = e5c.get("metrics", {})
    e7m = e7c.get("metrics", {})
    lines = [
        "% Generated by scripts/build_v9_paper_snippets.py; do not edit by hand.",
        f"\\newcommand{{\\VnineEtwoStatus}}{{{_tex(e2c.get('status'))}}}",
        f"\\newcommand{{\\VnineEthreeStatus}}{{{_tex(e3c.get('status'))}}}",
        f"\\newcommand{{\\VnineEfourStatus}}{{{_tex(e4c.get('status'))}}}",
        f"\\newcommand{{\\VnineEfiveStatus}}{{{_tex(e5c.get('status'))}}}",
        f"\\newcommand{{\\VnineEsevenStatus}}{{{_tex(e7c.get('status'))}}}",
        f"\\newcommand{{\\VnineEtwoSeeds}}{{{_tex(e2m.get('independent_seed_count'))}}}",
        f"\\newcommand{{\\VnineEtwoRows}}{{{_tex(e2m.get('transition_count'))}}}",
        f"\\newcommand{{\\VnineEtwoEffect}}{{{_num(e2m.get('shift_effect_mean'))}}}",
        f"\\newcommand{{\\VnineEtwoEffectCI}}{{[{_num(e2m.get('shift_effect_ci_low'))},\\,{_num(e2m.get('shift_effect_ci_high'))}]}}",
        f"\\newcommand{{\\VnineEthreeEffect}}{{{_num(e3m.get('effects', {}).get('pivot_voi_minus_proxy_only', {}).get('mean'))}}}",
        f"\\newcommand{{\\VnineEthreeEffectCI}}{{[{_num(e3m.get('effects', {}).get('pivot_voi_minus_proxy_only', {}).get('ci_low'))},\\,{_num(e3m.get('effects', {}).get('pivot_voi_minus_proxy_only', {}).get('ci_high'))}]}}",
        f"\\newcommand{{\\VnineEfourGain}}{{{_num(e4m.get('transition_minus_global_isc_mean'))}}}",
        f"\\newcommand{{\\VnineEfourGainCI}}{{[{_num(e4m.get('transition_minus_global_isc_ci_low'))},\\,{_num(e4m.get('transition_minus_global_isc_ci_high'))}]}}",
        f"\\newcommand{{\\VnineEfiveEffect}}{{{_num(e5m.get('pivot_voi_minus_proxy_cisr_reduction'))}}}",
        f"\\newcommand{{\\VnineEfiveEffectCI}}{{[{_num(e5m.get('pivot_voi_minus_proxy_ci_low'))},\\,{_num(e5m.get('pivot_voi_minus_proxy_ci_high'))}]}}",
        f"\\newcommand{{\\VnineEsevenEffect}}{{{_num(e7m.get('adaptive_effect_mean'))}}}",
        f"\\newcommand{{\\VnineEsevenEffectCI}}{{[{_num(e7m.get('adaptive_effect_ci_low'))},\\,{_num(e7m.get('adaptive_effect_ci_high'))}]}}",
        f"\\newcommand{{\\VnineEsevenSIRR}}{{{_num(_strategic_sirr(e7m))}}}",
        f"\\newcommand{{\\VnineClaimSummary}}{{E2C={_tex(e2c.get('status'))}; E3C={_tex(e3c.get('status'))}; E4C={_tex(e4c.get('status'))}; E5C={_tex(e5c.get('status'))}; E7C={_tex(e7c.get('status'))}}}",
    ]
    output = root / "paper/iclr2027/v9_results_macros.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def _decision(root: Path, experiment: str) -> dict[str, Any]:
    for suffix in ("confirmatory", "development", "smoke"):
        path = root / f"results/v9/{experiment}-{suffix}/scientific_decision.json"
        if path.is_file():
            payload = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(payload, dict):
                return payload
    return {"status": "MISSING", "metrics": {}}


def _strategic_sirr(metrics: dict[str, Any]) -> float | None:
    modes = metrics.get("by_mode", [])
    values = [float(row["SIRR"]) for row in modes if str(row.get("opponent_mode")) in {"best_response", "gradient_adaptive", "rl_evolutionary"}]
    return sum(values) / len(values) if values else None


def _num(value: Any) -> str:
    if value is None:
        return "--"
    numeric = float(value)
    return f"{numeric:.6f}" if abs(numeric) < 0.001 else f"{numeric:.4f}"


def _tex(value: Any) -> str:
    return "--" if value is None else str(value).replace("_", "\\_")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build V9 paper macros")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    output = build(args.root.resolve())
    print(json.dumps({"output": str(output)}, sort_keys=True))


if __name__ == "__main__":
    main()
