#!/usr/bin/env python3
"""Render paper-facing result macros from the frozen confirmatory artifacts.

The manuscript imports only these semantic macros.  This keeps numerical
claims out of hand-edited prose while leaving the machine experiment IDs in
the artifact manifests and audit reports.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, cast


def _load(root: Path, name: str) -> dict[str, Any]:
    path = root / f"results/v9/{name}-confirmatory/scientific_decision.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise TypeError(f"expected mapping in {path}")
    return payload


def _num(value: Any, *, digits: int = 4) -> str:
    if value is None:
        return "--"
    number = float(value)
    if abs(number) < 0.001:
        return f"{number:.6f}"
    return f"{number:.{digits}f}"


def _interval(low: Any, high: Any) -> str:
    return f"[{_num(low)},\\,{_num(high)}]"


def _method_row(metrics: dict[str, Any], environment: str, method: str) -> dict[str, Any]:
    for row in metrics.get("by_method_environment", []):
        if row.get("environment_id") == environment and row.get("method") == method:
            return cast(dict[str, Any], row)
    raise KeyError(f"missing method row: {environment}/{method}")


def build(root: Path) -> Path:
    e2 = _load(root, "e2c")
    e3 = _load(root, "e3c")
    e4 = _load(root, "e4c")
    e5 = _load(root, "e5c")
    e7 = _load(root, "e7c")
    m2 = e2["metrics"]
    m3 = e3["metrics"]
    m4 = e4["metrics"]
    m5 = e5["metrics"]
    m7 = e7["metrics"]
    e3_effects = m3["effects"]
    adaptive_mode_names = {"best_response", "gradient_adaptive", "rl_evolutionary"}
    strategic_modes = {
        str(row["opponent_mode"]): float(row["SIRR"])
        for row in m7["by_mode"]
        if str(row["opponent_mode"]) in adaptive_mode_names
    }
    if set(strategic_modes) != adaptive_mode_names:
        raise ValueError("registered adaptive opponent families are incomplete")
    family_cluster_counts = {int(row["cluster_n"]) for row in m7["by_mode"]}
    if len(family_cluster_counts) != 1:
        raise ValueError("opponent families do not share a matched seed-cluster count")
    matched_cluster_count = int(m7["independent_seed_count"])
    if matched_cluster_count != family_cluster_counts.pop():
        raise ValueError("adaptive effect must use the registered matched opponent-seed clusters")
    strategic_sirr = sum(strategic_modes.values()) / len(strategic_modes)
    congestion_proxy = _method_row(m3, "congestion_resource", "proxy_only")
    congestion_pivot = _method_row(m3, "congestion_resource", "pivot_voi")
    performative_proxy = _method_row(m3, "performative_control", "proxy_only")
    performative_pivot = _method_row(m3, "performative_control", "pivot_voi")
    lines = [
        "% Generated by scripts/build_v10_paper_snippets.py; do not edit by hand.",
        f"\\newcommand{{\\OperatorShiftSeeds}}{{{int(m2['independent_seed_count'])}}}",
        f"\\newcommand{{\\OperatorShiftRows}}{{{int(m2['transition_count'])}}}",
        f"\\newcommand{{\\OperatorShiftEffect}}{{{_num(m2['shift_effect_mean'])}}}",
        f"\\newcommand{{\\OperatorShiftEffectCI}}{{{_interval(m2['shift_effect_ci_low'], m2['shift_effect_ci_high'])}}}",
        f"\\newcommand{{\\ClosedLoopSeeds}}{{{int(m3['independent_seeds_by_environment']['congestion_resource'])}}}",
        "\\newcommand{\\ClosedLoopRounds}{40}",
        f"\\newcommand{{\\ClosedLoopProxyCISR}}{{{_num(congestion_proxy['CISR']['mean'])}}}",
        f"\\newcommand{{\\ClosedLoopPivotCISR}}{{{_num(congestion_pivot['CISR']['mean'])}}}",
        f"\\newcommand{{\\ClosedLoopPerformativeProxyCISR}}{{{_num(performative_proxy['CISR']['mean'])}}}",
        f"\\newcommand{{\\ClosedLoopPerformativePivotCISR}}{{{_num(performative_pivot['CISR']['mean'])}}}",
        f"\\newcommand{{\\ClosedLoopEffect}}{{{_num(e3_effects['pivot_voi_minus_proxy_only']['mean'])}}}",
        f"\\newcommand{{\\ClosedLoopEffectCI}}{{{_interval(e3_effects['pivot_voi_minus_proxy_only']['ci_low'], e3_effects['pivot_voi_minus_proxy_only']['ci_high'])}}}",
        f"\\newcommand{{\\OODSeeds}}{{{int(m4['independent_seed_count'])}}}",
        f"\\newcommand{{\\OODRows}}{{{int(m4['source_rows'])}}}",
        f"\\newcommand{{\\OODGain}}{{{_num(m4['transition_minus_global_isc_mean'])}}}",
        f"\\newcommand{{\\OODGainCI}}{{{_interval(m4['transition_minus_global_isc_ci_low'], m4['transition_minus_global_isc_ci_high'])}}}",
        f"\\newcommand{{\\EfficiencySeeds}}{{{int(m5['independent_seed_count'])}}}",
        f"\\newcommand{{\\EfficiencyPairedN}}{{{int(m5['paired_effect_n'])}}}",
        f"\\newcommand{{\\EfficiencyEffect}}{{{_num(m5['pivot_voi_minus_proxy_cisr_reduction'])}}}",
        f"\\newcommand{{\\EfficiencyEffectCI}}{{{_interval(m5['pivot_voi_minus_proxy_ci_low'], m5['pivot_voi_minus_proxy_ci_high'])}}}",
        f"\\newcommand{{\\StrategicSeeds}}{{{int(m7['independent_seed_count'])}}}",
        f"\\newcommand{{\\StrategicClusters}}{{{matched_cluster_count}}}",
        f"\\newcommand{{\\StrategicAdaptiveFamilies}}{{{len(strategic_modes)}}}",
        f"\\newcommand{{\\StrategicFamilySeedTraces}}{{{sum(int(row['cluster_n']) for row in m7['by_mode'])}}}",
        f"\\newcommand{{\\StrategicEffect}}{{{_num(m7['adaptive_effect_mean'])}}}",
        f"\\newcommand{{\\StrategicEffectCI}}{{{_interval(m7['adaptive_effect_ci_low'], m7['adaptive_effect_ci_high'])}}}",
        f"\\newcommand{{\\StrategicSIRR}}{{{_num(strategic_sirr)}}}",
        "% Strategic effect: mean of three adaptive family values within each matched seed; interval bootstraps matched seeds.",
        "% Strategic SIRR: unweighted mean of the three family-level SIRRs.",
        "% The external finance audit is observational and has no causal reversal estimate.",
    ]
    output = root / "paper/iclr2027/v10_results_macros.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Build semantic V10 paper macros")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    output = build(args.root.resolve())
    print(json.dumps({"output": str(output)}, sort_keys=True))


if __name__ == "__main__":
    main()
