from __future__ import annotations

from pathlib import Path

import pytest


def test_required_report_names_are_closed_and_include_finalizer() -> None:
    from experiments.v15.reports import REQUIRED_REPORTS

    assert "V15_FINAL_REPORT.md" in REQUIRED_REPORTS
    assert "V15_FIGURE_STATUS.md" in REQUIRED_REPORTS
    assert len(REQUIRED_REPORTS) == len(set(REQUIRED_REPORTS))


def test_repository_readme_uses_v15_finalizer() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")

    assert "experiments.v15 finalize" in readme
    assert "experiments.v10.finalize" not in readme


def test_number_audit_uses_adaptive_family_aggregation() -> None:
    from experiments.v15.reports import _number_audit

    report = _number_audit(Path("."))
    assert report["valid"]
    assert report["expected"]["StrategicAdaptiveFamilies"] == "3"
    assert report["expected"]["StrategicClusters"] == "30"
    assert report["expected"]["StrategicFamilySeedTraces"] == "90"
    assert report["expected"]["StrategicAllFamilySeedTraces"] == "150"


def test_release_metadata_is_neutralized(tmp_path: Path) -> None:
    from scripts.build_release_assets import build

    source = tmp_path / "paper/iclr2027/figures/v10"
    source.mkdir(parents=True)
    (source / "fig1.png").write_bytes(b"png")
    (source / "fig1.meta.json").write_text(
        '{"analysis_script":"experiments/v10/figures.py",'
        '"style_version":"pivot-v10-publication-style-1",'
        '"source":"figures/v10/fig1.csv"}\n',
        encoding="utf-8",
    )
    architecture = tmp_path / "paper/iclr2027/figures/fig3_pivot_architecture"
    architecture.with_suffix(".pdf").write_bytes(b"pdf")
    (tmp_path / "paper/iclr2027/v10_results_macros.tex").write_text(
        "% Generated by scripts/build_v10_paper_snippets.py\n", encoding="utf-8"
    )

    build(tmp_path)
    metadata = (tmp_path / "paper/iclr2027/figures/release/fig1.meta.json").read_text(
        encoding="utf-8"
    )
    assert "v10" not in metadata.casefold()
    assert "publication_figure_builder" in metadata


def test_language_audit_scans_transitively_included_body_sources(tmp_path: Path) -> None:
    from experiments.v15.audit_language import audit_language

    paper = tmp_path / "paper/iclr2027"
    paper.mkdir(parents=True)
    (paper / "main.tex").write_text(
        "\\documentclass{article}\n"
        "\\begin{document}\n"
        "\\input{body_fragment.tex}\n"
        "\\end{document}\n",
        encoding="utf-8",
    )
    (paper / "body_fragment.tex").write_text(
        "This body fragment must not expose V10 implementation labels.\n",
        encoding="utf-8",
    )

    report = audit_language(tmp_path)

    assert not report["valid"]
    assert report["body_version_tokens"] == ["V10"]
    assert "body_fragment.tex" in report["body_source_files"]


def test_resource_report_reads_yaml_protocol_values() -> None:
    from experiments.v15.reports import _load_protocol_config

    config = _load_protocol_config(Path("."))

    assert config["rounds"] == 30
    assert config["candidates_per_round"] == 4
    assert config["resource_plan"]["estimated"]["inspect_evaluations"] == 14400


def test_report_adapter_lines_use_project_local_runtime_probe() -> None:
    from experiments.v15.reports import _adapter_lines

    lines = _adapter_lines(Path("."))
    pi_line = next(line for line in lines.splitlines() if line.startswith("- Pi:"))
    assert "available" in pi_line


def test_build_lock_records_scaffold_runtime_probe(monkeypatch, tmp_path: Path) -> None:
    from experiments.v15.configuration import build_lock
    from experiments.v15.control_plane import AdapterStatus

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    for source, name in (
        (Path("configs/v15/confirmatory.yaml"), "confirmatory.yaml"),
        (Path("configs/v15/task_manifest.json"), "task_manifest.json"),
        (Path("configs/v15/external_versions.json"), "external_versions.json"),
    ):
        (config / name).write_bytes(source.read_bytes())

    monkeypatch.setattr(
        "experiments.v15.configuration.probe_adapters",
        lambda _root: [
            AdapterStatus("Inspect AI", "inspect_ai", "inspect", True, "x", "test"),
            AdapterStatus("mini-SWE-agent", "minisweagent", "mini-swe-agent", True, "y", "test"),
            AdapterStatus("Pi", None, "pi", False, None, "test"),
        ],
    )

    lock = build_lock(tmp_path)

    assert lock["scaffolds"]["primary"]["status"] == "available"
    assert lock["scaffolds"]["primary"]["runtime_version"] == "y"
    assert lock["scaffolds"]["replication"]["status"] == "adapter_not_available"
    assert lock["scaffolds"]["replication"]["runtime_source"] == "test"


def test_confirmatory_lock_is_not_overwritten_by_report_generation(tmp_path: Path) -> None:
    from experiments.v15.configuration import build_lock, ensure_lock

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    source_config = Path("configs/v15/confirmatory.yaml")
    source_tasks = Path("configs/v15/task_manifest.json")
    source_external = Path("configs/v15/external_versions.json")
    for source, name in ((source_config, "confirmatory.yaml"), (source_tasks, "task_manifest.json"), (source_external, "external_versions.json")):
        (config / name).write_bytes(source.read_bytes())

    lock_path = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock_path.parent.mkdir(parents=True)
    original = build_lock(tmp_path)
    lock_path.write_text(__import__("json").dumps(original, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    before = lock_path.read_bytes()

    ensured = ensure_lock(tmp_path, lock_path)

    assert ensured == lock_path
    assert lock_path.read_bytes() == before


def test_reproducibility_status_distinguishes_pinned_dev_from_confirmatory() -> None:
    from experiments.v15.audit_reproducibility import external_execution_status

    assert external_execution_status(
        {
            "dev-external-transition-audit": "COMPLETED",
            "dev-external-promotion": "COMPLETED",
            "dev-external-closed-loop": "COMPLETED",
            "dev-pi-replication": "COMPLETED",
            "dev-external-strategic-response": "PARTIAL",
            "dev-external-ablations": "COMPLETED",
        },
        confirmatory_open=False,
    ) == "PINNED_DEV_RUNTIME_VERIFIED; CONFIRMATORY_NOT_OPENED"
    assert external_execution_status({}, confirmatory_open=False).startswith("NOT_RUN")


def test_report_generation_materializes_footprint_diagnostic() -> None:
    from experiments.v15.reports import generate_reports

    result = generate_reports(Path("."))

    assert result["status"] == "BLOCKED"
    artifact = Path("artifacts/v15/footprint_analysis.json")
    report = Path("V15_FOOTPRINT_ANALYSIS.md")
    assert artifact.is_file()
    assert report.is_file()
    assert "DEV_ONLY" in report.read_text(encoding="utf-8") or "NOT_RUN" in report.read_text(encoding="utf-8")


def test_dev_partial_strategic_response_does_not_make_runtime_incomplete() -> None:
    from experiments.v15.reports import _dev_runtime_verified

    statuses = {
        "dev-external-transition-audit": "COMPLETED",
        "dev-external-promotion": "COMPLETED",
        "dev-external-closed-loop": "COMPLETED",
        "dev-pi-replication": "COMPLETED",
        "dev-external-strategic-response": "PARTIAL",
        "dev-external-ablations": "COMPLETED",
    }

    assert _dev_runtime_verified(statuses)


def test_existing_confirmatory_lock_with_bad_hash_is_rejected(tmp_path: Path) -> None:
    from experiments.v15.configuration import build_lock, ensure_lock

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    for source, name in ((Path("configs/v15/confirmatory.yaml"), "confirmatory.yaml"), (Path("configs/v15/task_manifest.json"), "task_manifest.json"), (Path("configs/v15/external_versions.json"), "external_versions.json")):
        (config / name).write_bytes(source.read_bytes())
    lock_path = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock_path.parent.mkdir(parents=True)
    lock = build_lock(tmp_path)
    lock["lock_hash"] = "tampered"
    lock_path.write_text(__import__("json").dumps(lock, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    import pytest

    with pytest.raises(ValueError, match="lock hash mismatch"):
        ensure_lock(tmp_path, lock_path)


def test_pre_outcome_lock_refresh_records_predecessor(tmp_path: Path) -> None:
    from experiments.v15.configuration import build_lock, refresh_pre_outcome_lock

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    for source, name in ((Path("configs/v15/confirmatory.yaml"), "confirmatory.yaml"), (Path("configs/v15/task_manifest.json"), "task_manifest.json"), (Path("configs/v15/external_versions.json"), "external_versions.json")):
        (config / name).write_bytes(source.read_bytes())
    lock_path = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock_path.parent.mkdir(parents=True)
    original = build_lock(tmp_path)
    lock_path.write_text(__import__("json").dumps(original, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    refreshed = refresh_pre_outcome_lock(tmp_path, lock_path)

    assert refreshed == lock_path
    payload = __import__("json").loads(lock_path.read_text(encoding="utf-8"))
    assert payload["predecessor_lock_hash"] == original["lock_hash"]
    assert (tmp_path / "experiments/v15/confirmatory_lock_history.jsonl").is_file()


def test_pre_outcome_lock_refresh_rejects_opened_outcomes(tmp_path: Path) -> None:
    from experiments.v15.configuration import build_lock, refresh_pre_outcome_lock

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    for source, name in ((Path("configs/v15/confirmatory.yaml"), "confirmatory.yaml"), (Path("configs/v15/task_manifest.json"), "task_manifest.json"), (Path("configs/v15/external_versions.json"), "external_versions.json")):
        (config / name).write_bytes(source.read_bytes())
    lock_path = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock_path.parent.mkdir(parents=True)
    lock = build_lock(tmp_path)
    lock["confirmatory_execution"] = "COMPLETED"
    unsigned = dict(lock)
    unsigned.pop("lock_hash")
    import hashlib

    from experiments.v15.protocol import canonical_json
    lock["lock_hash"] = hashlib.sha256(canonical_json(unsigned).encode()).hexdigest()
    lock_path.write_text(__import__("json").dumps(lock, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    with pytest.raises(PermissionError, match="outcomes"):
        refresh_pre_outcome_lock(tmp_path, lock_path)


def test_confirmatory_lock_opening_is_hashed_and_idempotent(tmp_path: Path) -> None:
    import json

    from experiments.v15.configuration import (
        _lock_digest,
        build_lock,
        is_confirmatory_open,
        open_confirmatory_lock,
    )

    config = tmp_path / "configs/v15"
    config.mkdir(parents=True)
    for source, name in (
        (Path("configs/v15/confirmatory.yaml"), "confirmatory.yaml"),
        (Path("configs/v15/task_manifest.json"), "task_manifest.json"),
        (Path("configs/v15/external_versions.json"), "external_versions.json"),
    ):
        (config / name).write_bytes(source.read_bytes())
    lock_path = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock_path.parent.mkdir(parents=True)
    lock_path.write_text(json.dumps(build_lock(tmp_path), sort_keys=True), encoding="utf-8")

    open_confirmatory_lock(tmp_path, lock_path, phase="transition_audit")
    opened = json.loads(lock_path.read_text(encoding="utf-8"))
    assert is_confirmatory_open(opened["confirmatory_execution"])
    assert opened["confirmatory_execution"]["status"] == "OPENED"
    assert opened["confirmatory_execution"]["phase"] == "transition_audit"
    assert opened["lock_hash"] == _lock_digest(opened)
    before = lock_path.read_bytes()

    open_confirmatory_lock(tmp_path, lock_path, phase="promotion_replay")

    assert lock_path.read_bytes() == before
