from __future__ import annotations

import json
from pathlib import Path


def test_neutral_asset_builder_materializes_paper_paths(tmp_path: Path) -> None:
    from scripts.build_release_assets import build

    source = tmp_path / "paper/iclr2027/figures/v10"
    source.mkdir(parents=True)
    (source / "fig1.png").write_bytes(b"png")
    architecture = tmp_path / "paper/iclr2027/figures/fig3_pivot_architecture"
    architecture.with_suffix(".pdf").write_bytes(b"pdf")
    (tmp_path / "paper/iclr2027/v10_results_macros.tex").write_text(
        "% Generated by scripts/build_v10_paper_snippets.py\n", encoding="utf-8"
    )
    paths = build(tmp_path)
    assert (tmp_path / "paper/iclr2027/figures/release/fig1.png").is_file()
    assert (tmp_path / "paper/iclr2027/figures/release/fig3_pivot_architecture.pdf").is_file()
    assert "v10" not in (tmp_path / "paper/iclr2027/results_macros.tex").read_text().casefold()
    assert len(paths) == 3


def test_public_release_contains_only_curated_artifacts(tmp_path: Path) -> None:
    from scripts.build_release_assets import build_public_release

    paper = tmp_path / "paper/iclr2027"
    paper.mkdir(parents=True)
    (paper / "pivot_iclr2027_submission.pdf").write_bytes(b"pdf")
    (paper / "pivot_iclr2027_supplementary.zip").write_bytes(b"zip")
    (paper / "submission_verification.json").write_text(
        json.dumps(
            {
                "package": "anonymous",
                "decision": "CONDITIONAL GO",
                "submission_ready": False,
                "blocking_gates": ["confirmatory study"],
                "pdf_pages": 14,
                "main_pages": 7,
                "machine_checks": {"supplement_content_clean": True},
                "archive_content_checks": {"valid": True},
                "archive_members": ["/opt/projects/private"],
            }
        ),
        encoding="utf-8",
    )
    lock = tmp_path / "experiments/v15/confirmatory_lock.json"
    lock.parent.mkdir(parents=True)
    lock.write_text('{"confirmatory_execution":"NOT_RUN"}\n', encoding="utf-8")
    (tmp_path / "V15_FINAL_REPORT.md").write_text("BLOCKED\n", encoding="utf-8")

    output = tmp_path / "release/v15"
    paths = build_public_release(tmp_path, output)
    names = {path.name for path in paths}
    assert names == {
        "paper.pdf",
        "supplementary.zip",
        "confirmatory_lock.json",
        "V15_FINAL_REPORT.md",
        "submission_verification.json",
        "README.md",
        "SHA256SUMS",
    }
    summary = json.loads((output / "submission_verification.json").read_text(encoding="utf-8"))
    assert "archive_members" not in summary
    assert "/opt/projects" not in (output / "submission_verification.json").read_text(encoding="utf-8")
    checksum_lines = (output / "SHA256SUMS").read_text(encoding="utf-8").splitlines()
    assert len(checksum_lines) == 6
